### ISSUE TITLE
made homework

### ISSUE THREAD

**Issue by Alexikon** [htl-perg-2019-20-5ahif/trippin-exercise-Alexikon#2]
I made the homework, here is the link:
https://github.com/htl-perg-2019-20-5ahif/trippin-exercise-Alexikon 

what I found out, is that the library at 2.1 does not support
[JsonPropertyName("UserName")]
Property

is that normal?

**Comment by rstropek** [comment]
Yes, you are right. [`JsonPropertyName`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertynameattribute#applies-to) is only supported in .NET Core 3.

The extra point is yours.

Greetings,
Rainer Stropek.
